[workspace]
members = ["smolrwkv", "smolrwkv-cli"]
resolver = "2"

[workspace.package]
version = "0.2.0"

[profile.release]
# Needed for profiling. Shouldn't affect performance.
debug = 1
#lto = "thin"
#codegen-units = 1
